#
# This file is used to define the services that will be used in the development environment.
# Comment, uncomment, or modify the services as needed.
#
version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: rest-api-postgres # Change the container name to match the service name
    environment:
      POSTGRES_DB: rest-api-development # Change the database name to match the service name
      POSTGRES_USER: database-user
      POSTGRES_PASSWORD: database-password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack
    container_name: rest-api-localstack # Change the container name to match the service name
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    environment: # https://docs.localstack.cloud/references/configuration
      - SERVICES=dynamodb,sns,sqs # Add or remove services as needed
      - DEBUG=0
      - DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  wiremock:
    image: wiremock/wiremock:latest
    container_name: rest-api-wiremock # Change the container name to match the service name
    ports:
      - '8081:8080'
    volumes:
      - ./test/mocks/files:/home/wiremock/__files
      - ./test/mocks/mappings:/home/wiremock/mappings
    entrypoint:
      ['/docker-entrypoint.sh', '--global-response-templating', '--disable-gzip', '--verbose']
volumes:
  postgres_data:
